# Generated by Django 3.2.9 on 2021-11-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hexuser',
            name='email',
            field=models.EmailField(blank=True, max_length=64, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='hexuser',
            name='is_enterprise',
            field=models.BooleanField(db_index=True, default=False, verbose_name='enterprise'),
        ),
        migrations.AlterField(
            model_name='hexuser',
            name='is_premium',
            field=models.BooleanField(db_index=True, default=False, verbose_name='premium'),
        ),
    ]
