# Generated by Django 3.2.9 on 2021-11-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211121_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='hexuser',
            name='rate',
            field=models.ManyToManyField(to='users.RateUser', verbose_name='rate'),
        ),
    ]
