# Generated by Django 3.2.9 on 2021-11-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_hexuser_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateuser',
            name='expiration',
            field=models.IntegerField(blank=True, default=None, verbose_name='link expiration (min)'),
        ),
    ]
