# Generated by Django 3.2.9 on 2021-11-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_rateuser_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateuser',
            name='expiration',
            field=models.IntegerField(default=None, null=True, verbose_name='link expiration (min)'),
        ),
    ]
