# Generated by Django 3.2.9 on 2021-11-21 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_rateuser_expiration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hexuser',
            name='rate',
        ),
        migrations.AddField(
            model_name='hexuser',
            name='rate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.rateuser', verbose_name='rate'),
            preserve_default=False,
        ),
    ]
