# Generated by Django 3.2.9 on 2021-11-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20211121_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateuser',
            name='expiration',
            field=models.BooleanField(default=False, verbose_name='link expiration'),
        ),
    ]
