# Generated by Django 3.2.9 on 2021-11-21 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_hexuser_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hexuser',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.rateuser', verbose_name='rate'),
        ),
    ]
