# Generated by Django 3.2.9 on 2021-11-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_hexuser_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='image size')),
            ],
        ),
        migrations.RemoveField(
            model_name='rateuser',
            name='size',
        ),
        migrations.AddField(
            model_name='rateuser',
            name='size',
            field=models.ManyToManyField(to='users.SizeImage', verbose_name='size'),
        ),
    ]
