# Generated by Django 3.2.9 on 2021-11-21 11:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=128, verbose_name='link to image')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='create')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
        ),
    ]
