# Generated by Django 3.2.9 on 2021-11-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211121_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='link',
            field=models.ImageField(upload_to='images', verbose_name='link to image'),
        ),
    ]
